global:
  scrape_interval: 15s

rule_files:
  - ./alerts.yaml

scrape_configs:
  - job_name: "file-based service discovery"
    file_sd_configs:
      - files:
        - "*.json"
        - "sd-hosts.yaml"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: 'username'
      password: 'test'

  - job_name: 'prom-srv'
    static_configs:
      - targets: ["prometheus:9090"]
    basic_auth:
      username: 'username'
      password: 'test'
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'blackbox-exporter-icmp'
    static_configs:
      - targets:
        - 8.8.8.8
        - 1.1.1.1
        - "google.com"
        - 1.2.3.1
    metrics_path: /probe
    params:
      module: [icmp]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115


  - job_name: 'blackbox-exporter-tcp-check'
    static_configs:
      - targets:
        - 8.8.8.8:53
        - 1.1.1.1:53
        - "google.com:443"
        - 1.2.3.1:80
    metrics_path: /probe
    params:
      module: [tcp_connect]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

#  - job_name: 'prom-srv-node-exporter'
#    static_configs:
#      - targets: ['192.168.56.220:9100']
#    basic_auth:
#      username: 'username'
#      password: 'test'
#    scheme: https
#    tls_config:
#      insecure_skip_verify: true


#  - job_name: 'mariadb-databases'
#    static_configs:
#      - targets: ['192.168.56.221:9204']
