# CSV metrics
UserParameter=demo.csv[*],/usr/bin/python3 /opt/zabbix/scripts/read_metrics.py csv /opt/zabbix/data/zabbix_metrics_demo.csv "$1" "$2"

# Excel metrics
UserParameter=demo.xlsx[*],/usr/bin/python3 /opt/zabbix/scripts/read_metrics.py xlsx /opt/zabbix/data/zabbix_metrics_demo.xlsx "$1" "$2"
